service: cognito-demo

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  # stage: dev
  region: ca-central-1

functions:
  index:
    handler: api/handler.hello
    # events:
    #   - http: GET hello
    events:
      - http:
          path: /hello
          method: GET
          # integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  second:
    handler: api/secondHandler.second
    events:
      - http: GET second

  email:
    handler: api/email/emailHandler.email
    events:
      - http: GET email
  # second:
  #   handler: second.sendMail
  #   events:
  #     - http: GET sendMail

resources:
  - ${file(./resources/cognito.yml)}
  - ${file(./resources/apigateway-authorizer.yml)}
