service: cognito-demo

frameworkVersion: "2"

# custom:
#   environment:
#     dev: ${file(./environment/dev.yml)}
#     prd: ${file(./environment/prd.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ca-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - usersTable
          - Arn

package:
  patterns:
    # - "!environment/**"
    - "!node_modules/**"
    - "!public/**"
    - "!src/**"
    - "!.next/**"
    - "!.github/**"

functions:
  first:
    handler: api/firsthandler.first
    events:
      - http:
          path: /hello
          method: GET
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  second:
    handler: api/secondHandler.second
    events:
      - http: GET second

  email:
    handler: api/email/emailHandler.email
    events:
      - http: GET email

  dynamodb:
    handler: api/dynamodb.dynamodb
    events:
      - http: GET dynamodb

resources:
  - ${file(./resources/cognito.yml)}
  - ${file(./resources/apigateway-authorizer.yml)}
  - ${file(./resources/dynamodb.yml)}
