service: cognito-demo

frameworkVersion: "2.35.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ca-central-1

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        # ExplicitAuthFlows:
        #   - ALLOW_USER_SRP_AUTH
        UserPoolId:
          Ref: UserPool
        GenerateSecret: False
