name: main CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

  production:
    runs-on: ubuntu-latest

    needs:
      - build

    # strategy:
    #   matrix:
    #     node-versions: [15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: serverless/github-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRO }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRO }}
          aws-region: ca-central-1
          args: deploy
      - run: sls deploy -v
